---
name: test

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]

  pull_request:

permissions:
  contents: read

jobs:
  test_linux:
    name: "test on linux"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: |
          script/setup --dev
      - name: test
        run: |
          test $(script/run --version) = $(cat wyoming_porcupine3/VERSION)
          script/lint
          script/test
